### ISSUE TITLE
Settings-based foreign key to User model

### ISSUE THREAD

**Issue by pydanny** [lawrencemq/django-online-users#1]
In your models:

``` python
user = models.OneToOneField(User)
```

should be replaced with:

``` python
user = models.OneToOneField(settings.AUTH_USER_MODEL)
```

**Comment by lawrencemq** [comment]
Oh interesting. I didn't know about that feature. Is this from the "Reusable apps and AUTH_USER_MODEL" section in https://docs.djangoproject.com/en/1.10/topics/auth/customizing/ ?

**Comment by pydanny** [comment]
Yup. 😁

**Comment by lawrencemq** [comment]
Fixed with a recent submission.
